### ISSUE TITLE
An error occurred in MPI_Isend

### ISSUE THREAD

**Issue by datawlb** [KnightKingWalk/KnightKing#10]
hi, thanks very much for your open soruce!
when i set a big worker, it has some problem about MPI_Isend

1. command:
./bin/deepwalk -g ./edge_2b.data_big -v 389727926 -w **1009727926** -s weighted -l 12 -o walks.txt --make-undirected

2.error:
 *** An error occurred in MPI_Isend
 *** reported by process [392036353,0]
 *** on communicator MPI_COMM_WORLD
 *** MPI_ERR_COUNT: invalid count argument
 *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)

If the parameter w is higher than 700million, we observe the above info

**Comment by ykwd** [comment]
Thanks for usage. I think this is because KnightKing uses MPI for communications. While invoke the MPI send function, one parameter is "count". This parameter specifies the size of the message, and the type is int. So when the message size is larger than the maximum value of int, this parameter may become negative, which is detected as invalid by MPI.

We may improve this in the future. While for now you can set "-r 0.5" or "-r 0.2" if there are huge number of walkers. ""-r" option will break random walk into multiple epochs. Each iteration has rate% walkers. Use this option if memory is not enough to hold all walkers and their paths." Sorry for the inconvenience.

**Comment by datawlb** [comment]
thanks for your detailed reply! it works.
